name: Deploy Frontend to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:$GITHUB_SHA .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:$GITHUB_SHA

      - name: Deploy frontend to Kubernetes using Helm
        run: |
          helm upgrade --install frontend ./charts/frontend
